<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7762" started-at="2019-09-03T10:53:04Z" finished-at="2019-09-03T10:53:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7762" started-at="2019-09-03T10:53:04Z" finished-at="2019-09-03T10:53:12Z">
      <class name="com.Testing_Pack.Reportngtest2">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.Testing_Pack.Reportngtest2@7b69c6ba]" name="setup" is-config="true" duration-ms="6534" started-at="2019-09-03T10:53:04Z" finished-at="2019-09-03T10:53:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="mul_Test()[pri:1, instance:com.Testing_Pack.Reportngtest2@7b69c6ba]" name="mul_Test" duration-ms="325" started-at="2019-09-03T10:53:11Z" finished-at="2019-09-03T10:53:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [25] but found [20]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [25] but found [20]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.Testing_Pack.Reportngtest2.mul_Test(Reportngtest2.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mul_Test -->
        <test-method status="PASS" signature="div_Test()[pri:2, instance:com.Testing_Pack.Reportngtest2@7b69c6ba]" name="div_Test" duration-ms="263" started-at="2019-09-03T10:53:11Z" finished-at="2019-09-03T10:53:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- div_Test -->
        <test-method status="PASS" signature="Close()[pri:0, instance:com.Testing_Pack.Reportngtest2@7b69c6ba]" name="Close" is-config="true" duration-ms="620" started-at="2019-09-03T10:53:11Z" finished-at="2019-09-03T10:53:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
      </class> <!-- com.Testing_Pack.Reportngtest2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
